theme: jekyll-theme-hacker
name: Rafael Naufal's blog
title: Rafael Naufal's blog
title_separator: "-"
description: Communicating my thoughts on software development
repository: "rnaufal/rnaufal.github.io"
twitter:
  username: rnaufal
footer-links:
  github: rnaufal
  twitter: rnaufal
